### ISSUE TITLE
jwt

### ISSUE THREAD

**Issue by RBleyenberg** [mohiva/play-silhouette-seed#104]
Howdy,

i'm trying to implement a jwt token.

within defaultEnv 

trait DefaultEnv extends Env {
  type I = User
  type A = JWTAuthenticator
}
and SilhouetteModule 

  @Provides
  def provideEnvironment(
    userService: UserService,
    authenticatorService: AuthenticatorService[JWTAuthenticator],
    eventBus: EventBus): Environment[DefaultEnv] = {

    Environment[DefaultEnv](
      userService,
      authenticatorService,
      Seq(),
      eventBus
    )
  }

also the silhouette.conf

  # JWT authenticator settings
  authenticator.headerName="X-Auth-Token"
  authenticator.issuerClaim="play-angular-silhouette"
  authenticator.encryptSubject=true
  authenticator.authenticatorExpiry=12 hours
  authenticator.sharedSecret="changeme"

  authenticator.rememberMe.authenticatorExpiry=30 days
  authenticator.rememberMe.authenticatorIdleTimeout=5 days

  authenticator.crypter.key = "[changeme]" // A unique encryption key

i'm getting the following error and not sure how to procede.

1) No implementation for com.mohiva.play.silhouette.api.services.AuthenticatorService<com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticator> was bound.
  while locating com.mohiva.play.silhouette.api.services.AuthenticatorService<com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticator>
    for the 2nd parameter of modules.SilhouetteModule.provideEnvironment(SilhouetteModule.scala:91)
  at modules.SilhouetteModule.provideEnvironment(SilhouetteModule.scala:91) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.SilhouetteModule)

2) No implementation for com.mohiva.play.silhouette.api.services.AuthenticatorService<com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticator> was bound.
  at modules.SilhouetteModule.provideEnvironment(SilhouetteModule.scala:91) (via modules: com.google.inject.util.Modules$OverrideModule -> modules.SilhouetteModule)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:84)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
        at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
        at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
        at play.core.server.DevServerStart$$anon$1.$anonfun$reload$3(DevServerStart.scala:174)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[info] Compiling 1 Scala source to C:\Users\R Bleyenberg\dare-projects\dare-seed\server\target\scala-2.12\classes...
[error] C:\Users\R Bleyenberg\dare-projects\dare-seed\server\app\modules\SilhouetteModule.scala:93: type mismatch;
[error]  found   : com.mohiva.play.silhouette.api.services.AuthenticatorService[com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticator]
[error]  required: com.mohiva.play.silhouette.api.services.AuthenticatorService[utils.authentication.DefaultEnv#A]
[error]     (which expands to)  com.mohiva.play.silhouette.api.services.AuthenticatorService[com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticator]
[error]       authenticatorService,
[error]       ^
[error] one error found
[error] (server/compile:compileIncremental) Compilation failed
[info] Compiling 1 Scala source to C:\Users\R Bleyenberg\dare-projects\dare-seed\server\target\scala-2.12\classes...
[error] C:\Users\R Bleyenberg\dare-projects\dare-seed\server\app\modules\SilhouetteModule.scala:93: type mismatch;
[error]  found   : com.mohiva.play.silhouette.api.services.AuthenticatorService[com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticator]
[error]  required: com.mohiva.play.silhouette.api.services.AuthenticatorService[utils.authentication.DefaultEnv#A]
[error]     (which expands to)  com.mohiva.play.silhouette.api.services.AuthenticatorService[com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticator]
[error]       authenticatorService,
[error]       ^
[error] one error found
[error] (server/compile:compileIncremental) Compilation failed
[info] Compiling 1 Scala source to C:\Users\R Bleyenberg\dare-projects\dare-seed\server\target\scala-2.12\classes...
[error] C:\Users\R Bleyenberg\dare-projects\dare-seed\server\app\modules\SilhouetteModule.scala:93: type mismatch;
[error]  found   : com.mohiva.play.silhouette.api.services.AuthenticatorService[com.mohiva.play.silhouette.impl.authenticators.CookieAuthenticator]
[error]  required: com.mohiva.play.silhouette.api.services.AuthenticatorService[utils.authentication.DefaultEnv#A]
[error]     (which expands to)  com.mohiva.play.silhouette.api.services.AuthenticatorService[com.mohiva.play.silhouette.impl.authenticators.JWTAuthenticator]
[error]       authenticatorService,
[error]       ^
[error] one error found
[error] (server/compile:compileIncremental) Compilation failed

Many thx upfront.

**Comment by akkie** [comment]
https://github.com/mohiva/play-silhouette-seed/blob/master/.github/ISSUE_TEMPLATE.md

> This is an issue tracker, used to manage and track the development of Silhouette. It is not a support system and so it is not a place to ask questions or get help. If you're not sure if you have found a bug, the best place to start is with either the forum or Gitter channel. If you have a feature request, the forum is better than the issue tracker to discuss it.

If you start a new question, please take the time to create a meaningful title and also format the message properly, so that the code can be read by humans.
