### ISSUE TITLE
issues get closed after 2 days without response, help or reason 

### ISSUE THREAD

**Issue by hubca** [mohiva/play-silhouette-seed#123]
Why did my very legitimate question get closed without resolution or response after 2 days?
----
I have REST API endpoints that I want to secure to ensure that only those authorised can access or internally (via Play's native Scala Web Services). I previously have used this method directly from the oAuth documentation but I wanted a more comprehensive solution and therefore integrated this repo into my project. But so far; I've been unsuccessful in fathoming how to integrate this in protecting my CRUD endpoints. Any help/pointers appreciated!

**Comment by akkie** [comment]
Hi,

From https://github.com/mohiva/play-silhouette-seed/blob/master/.github/ISSUE_TEMPLATE.md:
> Are you looking for help?
This is an issue tracker, used to manage and track the development of Silhouette. It is not a support system and so it is not a place to ask questions or get help. If you're not sure if you have found a bug, the best place to start is with either the forum or Gitter channel. If you have a feature request, the forum is better than the issue tracker to discuss it.

The post was tagged as question.

**Comment by hubca** [comment]
It’s relevant to the repo not Silhouette as a whole. It would be useful and I would be grateful if you used your energy to help how to secure api endpoints_
