### ISSUE TITLE
Example of BearerTokenAuthenticator

### ISSUE THREAD

**Issue by davidseth** [mohiva/play-silhouette-seed#18]
Could you put a working example of BearerTokenAuthenticator into this seed project? I am trying to figure out Silhouette and have looked at the https://github.com/merle-/silhouette-rest-seed example, but unfortunately it is out-of-date. It is based on the older HeaderAuthenticator.

I have been banging my head on this for about a day and can not get it to work, so a built-in example would be wonderful.

Thank you.

**Comment by akkie** [comment]
@davidseth I've finished the work on the [Angular seed Template](https://github.com/mohiva/play-silhouette-angular-seed) which uses token based authentication.

Let me know if you have further questions.

**Comment by davidseth** [comment]
Wow. Great. Will take a look today.

**Comment by mohitjaggi** [comment]
How can I get part of my application use Cookies and and another part use bearer tokens?

**Comment by akkie** [comment]
You need to define different environments: http://www.silhouette.rocks/docs/environment

**Comment by mohitjaggi** [comment]
got it. Thanks Christian!

**Comment by Raymond26** [comment]
+1 for an actual BearerTokenAuthenticator implementation and not just JWT.  Getting a  `AuthenticatorRepository`setup for the `BearerTokenAuthenticatorService is not clear from the docs and I'm not very skilled with Guice dependency injection.  I was able to figure it to run but it took a while and I'm not even sure if this even works properly.

```
bind(classOf[CacheLayer]).to(classOf[PlayCacheLayer])
...
val authenticatorRepository = new CacheAuthenticatorRepository[BearerTokenAuthenticator](cacheLayer)
    new BearerTokenAuthenticatorService(settings, authenticatorRepository, idGenerator, clock)
```
