### ISSUE TITLE
[error] c.m.p.s.a.e.AuthenticationException - [Silhouette][credentials] Could not find auth info for given credentials

### ISSUE THREAD

**Issue by dsanchez31** [mohiva/play-silhouette-seed#30]
Hi,

I run this example.

The singUp works but when I try singIn with the newly created user, the browser stills in the signIn page (no home redirection) and the given log is output ;

[error] c.m.p.s.a.e.AuthenticationException - [Silhouette][credentials] Could not find auth info for given credentials

Could you tell me why ?

Thanks !

**Comment by akkie** [comment]
I think this is because of https://github.com/mohiva/play-silhouette

I'll try to fix this asap.

**Comment by dsanchez31** [comment]
Thanks ! I'm waiting for your fix :) !

**Comment by akkie** [comment]
It should work now.
