### ISSUE TITLE
Seed demo for v1.0 offline

### ISSUE THREAD

**Issue by sne11ius** [mohiva/play-silhouette-seed#32]
You probably know this, but if not: the "old" demo @ http://play-silhouette-seed.mohiva.cloudbees.net/ is offline.
I think it would be nice to be able to try this one until versions 2.0 of silhouette lib & seed are final.

**Comment by akkie** [comment]
@sne11ius Please see https://github.com/mohiva/play-silhouette-seed/issues/25#issuecomment-70979423

2.0 is planned at the end of the week and CloudBees doesn't offer a free application tier anymore.
