### ISSUE TITLE
Inject providers as Singleton (or just Environment)

### ISSUE THREAD

**Issue by studiodev** [mohiva/play-silhouette-seed#33]
I noticed that in SilhouetteModule.scala, only the [YahooProvider](https://github.com/mohiva/play-silhouette-seed/blob/master/app/utils/di/SilhouetteModule.scala#L247) is provided as a Singleton, not the others (Twitter, Google...)

Unless Yahoo is a special case, all providers should be injected with the same scope for better uniformity.

I'm not an expert in Guice, but I think we could just inject `Environment` as a singleton, it will save some resources.

What do you think about that?

**Comment by akkie** [comment]
I don't know why the YahooProvider is injected as singleton. It's certainly not a special case.

For Silhouette I can say that the lib is thread safe but for components used by Silhouette I cannot. The DAOs in the seed template are also not thread safe because they use mutable maps to store the data. So I'm not sure if we should provide the Environment as singleton. What do you think?

**Comment by studiodev** [comment]
The DAOs are binded manually (`bind[UserDAO].to[UserDAOImpl]`), so they will never been in a singleton.

Like I've said I just begin to use Guice, but by looking the `Environment` dependencies, I think it's OK to just create it one time.

    userService: UserService,
    authenticatorService: AuthenticatorService[SessionAuthenticator],
    eventBus: EventBus,
    credentialsProvider: CredentialsProvider,
    facebookProvider: FacebookProvider,
    googleProvider: GoogleProvider,
    clefProvider: ClefProvider,
    twitterProvider: TwitterProvider,
    yahooProvider: YahooProvider

But if we are not sure, we can just set the Singleton on providers, it will be more careful.

**Comment by akkie** [comment]
But the `UserDAO` is injected into the `UserService` which is injected into the `Environment`.

I think the providers are OK. Would you create a pull request? I'm currently very busy with the 2.0 release.

**Comment by studiodev** [comment]
Yes of course.

I will do some tests around Environment, but just edit the providers for now.

**Comment by akkie** [comment]
Cool, thanks!

**Comment by studiodev** [comment]
In fact it's quite easy to test which class need to be a singleton or not.

Currently, all classes are re-created on each request (providers, environment, service and daos)
The only things created one time are the DAO objects which store the mutable map.
All instances could be shared (no non-threadsafe reference).
So in fact we could make all the dependencies as singleton.

Then I've checked the [Guice recommendation](https://github.com/google/guice/wiki/Scopes#choosing-a-scope) about scoping. 

> If the object is stateless and inexpensive to create, scoping is unnecessary. Leave the binding unscoped and Guice will create new instances as they're required.

So I think we should just get rid of the Yahoo singleton.
Is it ok for you?

**Comment by akkie** [comment]
Yes, it's OK for me.
