### ISSUE TITLE
Missing config value: clef.authorizationURL

### ISSUE THREAD

**Issue by janimattiellonen** [mohiva/play-silhouette-seed#38]
I get the following error:

ProvisionException: Guice provision errors: 1) Error in custom provider, java.util.NoSuchElementException: None.get at utils.di.SilhouetteModule.provideClefProvider(SilhouetteModule.scala:215) while locating com.mohiva.play.silhouette.impl.providers.oauth2.ClefProvider at utils.di.SilhouetteModule.provideEnvironment(SilhouetteModule.scala:77) while locating com.mohiva.play.silhouette.api.Environment<models.User, com.mohiva.play.silhouette.impl.authenticators.SessionAuthenticator> for parameter 0 at controllers.ApplicationController.<init>(ApplicationController.scala:18) while locating controllers.ApplicationController 1 error

If I add the following line to silhouette.conf, it works:

clef.authorizationURL="https://SOME-URL-HERE"

**Comment by akkie** [comment]
Which version do you use? In version 2.0RC1 this is optional. https://github.com/mohiva/play-silhouette/pull/269

**Comment by akkie** [comment]
I close this for now. If you have further issues, please open it again.
