### ISSUE TITLE
some inaccuracy

### ISSUE THREAD

**Issue by AndreyLadniy** [mohiva/play-silhouette-seed#41]
1. In all DAOs extended DelegableAuthInfoDAO
/**
   * Saves the OAuth1 info.
   *
   * @param loginInfo The login info for which the auth info should be saved.
   * @param authInfo The OAuth1 info to save.
   * @return The saved OAuth1 info or None if the OAuth1 info couldn't be saved.
   */

  def save(loginInfo: LoginInfo, authInfo: OAuth1Info): Future[OAuth1Info] = {

return Option in descrition

2. In SocialAuthController line 44, SignUpController line 65, CredentialsAuthController line 45 ('authenticator <- env.authenticatorService.create(user.loginInfo)')
 you use 'user.loginInfo', but may be better 'profile.loginInfo' for common case (if somebody create User without loginInfo)

**Comment by akkie** [comment]
Hi,

could you please create a pull request for the first case? For the second case that could be changed. But this example uses an identity with a `LoginInfo`. If you create a pull request too, then it's OK for me.

Cheers,
Christian

**Comment by AndreyLadniy** [comment]
Ok. One more question: Why does the class User (Identity) have loginInfo when we have an environment with the authenticator, which is required to be login information? Maybe I missed something conceptual?

**Comment by akkie** [comment]
The `LoginInfo` is the user ID of Silhouette. In this sample implementation this is needed to [retrieve](https://github.com/mohiva/play-silhouette/blob/master/silhouette/app/com/mohiva/play/silhouette/api/services/IdentityService.scala#L37) a user based on this info. It is also possible to link multiple login info to a single user. In this case you must provide a mapping between a unique user ID and the different login information.

**Comment by AndreyLadniy** [comment]
Yes of course. I have in DB layer with two tables: login info + user id and user info. One user can have multiple accounts (login info). Since we started talking about linking, how can i realize it? I try in SocialAuthController authenticate action change to UserAwareAction, and when i sign in after sign in i have cerrent user in request but what's next?

**Comment by akkie** [comment]
Please take a look at the [Rest Seed example](https://github.com/merle-/silhouette-rest-seed/search?utf8=%E2%9C%93&q=link). It provides linking of multiple providers.

**Comment by AndreyLadniy** [comment]
I can't understand where are the data for the link(provider) function in controller? From the provider, but how he takes RedirectUrl for link function. As I understand it, the user accounts binding is only possible after provider authentication?

**Comment by akkie** [comment]
I think that gets a bit off-topic. For such questions it is better to use the [mailing list](https://groups.google.com/forum/#!forum/play-silhouette). Please create a topic there and I'll see I can help you.

For the inaccuracy you find in the Seed, are you willing to create a pull request?

**Comment by AndreyLadniy** [comment]
I haven't figured out how to use github, so cannot create pull requests.

**Comment by akkie** [comment]
Fixed #44
