### ISSUE TITLE
embed is not work, can you fix this project ?

### ISSUE THREAD

**Issue by misercoal** [mohiva/play-silhouette-seed#47]

**Comment by akkie** [comment]
A detailed explaination of the issue would be nice. Which version do you use?

**Comment by misercoal** [comment]
hi, akkie.
Thanks for response. The seed project itself can't run well.  I run this a week ago, and I found in 
SignUpController, result <- env.authenticatorService.embed(value, Future.successful(
                Redirect(routes.ApplicationController.index())
              )).

the embed method now need implicit request: RequestHeader.
I'll be very nice if you can fix this.
btw, I'm using silhouette now, and I'll use weibo auth2. So maybe I'll send a pr to you recently.

**Comment by akkie** [comment]
I'm not sure I can follow you. The `embed` method needs this implicit request since it's first introduction in the 2.0 SNAPSHOT. There is nothing new. Do you have a compiler error?

**Comment by misercoal** [comment]
Yea. I'm mean 
![image](https://cloud.githubusercontent.com/assets/11939870/7218923/b64c8dca-e6b9-11e4-8b45-fb890eb9e320.png)

**Comment by akkie** [comment]
This seems like an error in your IDE. As you can see in this [line](https://github.com/mohiva/play-silhouette-seed/blob/master/app/controllers/SignUpController.scala#L42), the implicit request is available and will be used. Have you tried to run or compile the project?

**Comment by misercoal** [comment]
I can see the implict request.
![image](https://cloud.githubusercontent.com/assets/11939870/7218970/5540d4d4-e6bc-11e4-8be0-aeb0a3151916.png)

**Comment by akkie** [comment]
This is strange. I do not have such a issue! What version do you use? Do you use 2.0 or 2.1-SNAPSHOT?

**Comment by akkie** [comment]
Ahh, now I see it. I've used an old locally deployed SNAPSHOT version. With the actual version I've also the issue.

**Comment by misercoal** [comment]
Hey, akkie. I wonder when will the new stable version ? Also, when will you support weibo. I know it's in future. If weibo will not come soon, I think I should write it by myself.

**Comment by akkie** [comment]
@misercoal Please see #48. The 2.1 release is planned roughly in two months. Weibo support is on the to-do list but I don't know if I find the time to implement it in 2.1. It would be nice if you could create a pull request.
