### ISSUE TITLE
Question regarding the versions...

### ISSUE THREAD

**Issue by santoshv98** [mohiva/play-silhouette-seed#49]
I see that you are using a 2.3 version of Play with this project and a recent version of play-silhouette. And I see that play-silhouette has been updated for Play-2.4-RC1. 

Are there any plans to update this to the latest as well? 

If I use the latest version of the Main project (play-silhouette) and move this to the latest version of Play, do you anticipate any issues due to the change in Play version? May be I should fork and try it out with the latest libraries.

**Comment by akkie** [comment]
I'll start to update the Seed template today.

**Comment by akkie** [comment]
Fixed with #50
