### ISSUE TITLE
Add security filters to project

### ISSUE THREAD

**Issue by wsargent** [mohiva/play-silhouette-seed#56]
CSRFFilter and SecurityHeadersFilter should be added to the build and be running by default.  Will add a PR.

**Comment by anotherhale** [comment]
The following Content Security Policy needs to be applied to create the white list of allowed cross-site requests for avatar images, CDN hosted CSS, fonts, and javascript.

(I would do a pull request, but I currently don't have access to a computer where I can do a git push.) 

# Security Filter Configuration - Content Security Policy
#
#play.filters.headers.contentSecurityPolicy
# default-src
# 'self'
# img-src (avatar images)
# https://s.yimg.com (yahoo!)
# https://fbcdn-profile-a.akamaihd.net (facebook)
# https://pbs.twimg.com (twitter)
# https://lh5.googleusercontent.com (google)
# https://m.vk.com (vk)
# style-src
# http://cdnjs.cloudflare.com
# 'unsafe-inline' (in-line css found in bootstrap.min.js)
# font-src
# http://fonts.gstatic.com
# http://fonts.googleapis.com
# script-src
# https://clef.io
play.filters.headers.contentSecurityPolicy= "default-src 'self' img-src https://m.vk.com https://s.yimg.com https://fbcdn-profile-a.akamaihd.net https://pbs.twimg.com https://lh5.googleusercontent.com style-src 'unsafe-inline' http://cdnjs.cloudflare.com font-src http://fonts.gstatic.com http://fonts.googleapis.com script-src https://clef.io"

**Comment by akkie** [comment]
@anotherhale Is this configuration really needed to run this template? Maybe we can add it to the docs as an example configuration?
