### ISSUE TITLE
build.sbt

### ISSUE THREAD

**Issue by renexdev** [mohiva/play-silhouette-seed#64]
Hello there! I'm new with Play Framework, I'm looking an easy-to-use module for implementing user logging. When I try your example 
I get some issues with the line...
```
  "com.mohiva" %% "play-silhouette-testkit" % "3.0.0" % "test",
  specs2 % Test,
```

It seems doesnt follow the same structure than the previous defined code lines.
On the other hand, there is another issue with the code line 
```
routesGenerator := InjectedRoutesGenerator 
```
the compiler doesnt find the function
Thanks for any help,
Cheers,
Rene

**Comment by akkie** [comment]
Please could you post the compiler messages?
What version of `sbt` or `activator` do you use?

**Comment by renexdev** [comment]
Thanks akkie for your concern, 
My system is an Ubuntu 14.04 LTS, I've just added the last version of Play: activator-1.3.5, and I have scala version 2.11.1, sbt  0.13.8
The problem seems to arise with the error
------------------------------------------------------------------------------------------
java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0
------------------------------------------------------------------------------------------
Then to fix that I changed the version in /project/plugings.sbt, the  sbt-plugin to 2.3.9 (the one that doesnt give an error) 
And get the two as I told you...
For the specs2 issue the error is:
------------------------------------------------------------------------------------------
[info] Loading project definition from /home/.../play-silhouette-seed-master/project
/home/.../play-silhouette-seed-master/build.sbt:23: error: not found: value specs2
  specs2 % Test,
  ^
[error] Type error in expression
------------------------------------------------------------------------------------------
I'm trying to replace with something like "org.specs2" %% "specs2" % "2.3.7" % "test", but the compile doesnt find the dependency,I have to investigate a little more...
And for routesGenerator := InjectedRoutesGenerator 
I tried to update my Java version from 7 to 8, but doesnt solve my problem
Seems something to do with sbt version, any suggestions? 
Thanks in advance,
Rene

**Comment by renexdev** [comment]
I'm following the steps in http://www.scala-sbt.org/0.13/tutorial/Installing-sbt-on-Linux.html to update sbt in my ubuntu, I'll tell you what happens when it finishes...

**Comment by renexdev** [comment]
Works NOW!!!! Thanks! 
Be aware that sbt must be  0.13.9! 
Tested in Ubuntu 14.04 LTS, Activator-1.3.5, Scala 2.11.1, sbt 0.13.9, Java 8
Cheers

**Comment by ezzahraoui** [comment]
What's your Java version ?

-----Original Message-----

**Comment by renexdev** [comment]
It was for the java 8 oracle version (I prefer the jdk but I'm lazy now to install it properly), but now I've just test it with my java-7-openjdk-amd64, and shows me again the following error:
[error] java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0
So, must be java 8 (it should also work with openjdk, I have to try it later) & sbt 0.13.9
Cheers

**Comment by akkie** [comment]
Yep, Play 2.4 needs Java 8.

**Comment by renexdev** [comment]
A+
