### ISSUE TITLE
New Feature suggestion - Show and enforce password strength

### ISSUE THREAD

**Issue by mslinn** [mohiva/play-silhouette-seed#87]
_PART V: Checking Password Strength_ of [The definitive guide to form-based website authentication](http://stackoverflow.com/questions/549/the-definitive-guide-to-form-based-website-authentication) has a nice explanation of why it is important to show and enforce password strength. 

> With no minimum password strength requirements, 2% of users use one of the top 20 most common passwords. Meaning: if an attacker gets just 20 attempts, 1 in 50 accounts on your website will be crackable.

See also [Throttle login attempts #489](https://github.com/mohiva/play-silhouette/issues/489)

**Comment by akkie** [comment]
I think this would be a nice feature which could be implemented as an utility component. How would you implement the rule set?

**Comment by mslinn** [comment]
Best if this runs on the browser since there is no need for server interaction. [Dropbox’s zxcvbn](https://nulab-inc.com/blog/nulab/password-strength/), a JavaScript implementation, looks pretty good.

**Comment by akkie** [comment]
But this doesn't enforce password strength on the server side. It would also be great if it's possible to define some password rules server side. What do you think?

**Comment by mslinn** [comment]
There is a Java version of zxcvbn, so it could run server-side and could reject weak passwords. Minimum password strength could be a configurable parameter.

**Comment by mslinn** [comment]
A rule-based password generator could also be provided, for example [password-generator](https://github.com/bermi/password-generator)

**Comment by mslinn** [comment]
I added the ability to display password strength [in my fork](https://github.com/mslinn/play-silhouette-seed). It does not display the strength color bar in Chrome, but works fine in Firefox.

**Comment by akkie** [comment]
Would you create a pull request?

**Comment by mslinn** [comment]
Sure. I hope the squashing works better than last time!

**Comment by akkie** [comment]
Fixed with #88

**Comment by mslinn** [comment]
Although this feature works on Mac & Windows, it does not on Chrome for Linux. Filed a bug on the Chrome Issue Tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=632171

**Comment by akkie** [comment]
It works for me in Chromium on Linux. Not sure which version I've currently because I'm on my mobile.

**Comment by mslinn** [comment]
[Here is the solution](http://stackoverflow.com/questions/38573680/html5-meter-styling-in-chrome) to the Linux problem. Just need to [delete this line](https://github.com/mohiva/play-silhouette-seed/blob/master/public/styles/main.css#L106).
