### ISSUE TITLE
Delete play.http.requestHandler HOCON entry

### ISSUE THREAD

**Issue by mslinn** [mohiva/play-silhouette-seed#93]
`application.conf` contains this:

```
# Registers the request handler
# ~~~~~
play.http.requestHandler = "play.api.http.DefaultHttpRequestHandler"
```

However, the [Play source code](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala#L76-L85) comments seem to be more current than the [current Play docs](https://www.playframework.com/documentation/2.5.x/ScalaHttpRequestHandlers#Performance-notes).

tl;dr - delete this configuration entry

**Comment by akkie** [comment]
Please see #65. I'm not sure if this is still valid.

**Comment by mslinn** [comment]
#65 is references an older version of Play and no longer applies. This issue is valid as described.

**Comment by akkie** [comment]
Sorry, but I cannot find any information in the Play source code that nullify the current Play docs. Please could you point me to the right direction.

**Comment by mslinn** [comment]
Please see the link to the Play source code that I provided above.

**Comment by akkie** [comment]
I've looked into the source code and couldn't find any information that nullify the current Play docs :confused:

**Comment by mslinn** [comment]
"Technically, this is not the default request handler that Play uses, rather, the JavaCompatibleHttpRequestHandler is the default one, in order to provide support for Java actions."

**Comment by akkie** [comment]
But in my opinion this does not imply that there is no performance issue as described in the docs. And I think for a Scala application the `DefaultHttpRequestHandler` can be used as default request handler, because we must not support Java actions :wink: 

Maybe we should ask in the gitter channel if the documentation is still valid.

**Comment by mslinn** [comment]
My concern is that this little-known setting makes the sample project incompatible with Java `Action`s. It would be fine to keep this setting unchanged, provided that there is a comment next to it warning users that it disallows Java `Action`s, and they should remove the setting if they need Java `Action`s. Also the warning should be included in any future step-by-step documentation such as **How to Incorporate play-silhouette-seed Into Your Project**.

**Comment by akkie** [comment]
Silhouette itself is completely incompatible with Java. I thought this was clear. I've added an information to the [documentation page](http://silhouette.mohiva.com/v4.0/docs/introduction).
