### ISSUE TITLE
How to add generated password to Slick evolution

### ISSUE THREAD

**Issue by viennv1709** [mohiva/play-silhouette-seed#97]
I have a sql file for slick evolution. Because Silhouette is using BCryptPasswordHasher, so each generated password for the same plain password is different. How to add generated password to Slick evolution.

**Comment by akkie** [comment]
### Are you looking for help?

This is an issue tracker, used to manage and track the development of Silhouette. It is not a support system and so it is not a place to ask questions or get help. If you're not sure if you have found a bug, the best place to start is with either the [users mailing list](https://groups.google.com/forum/#!forum/play-silhouette) or [Gitter channel](https://gitter.im/mohiva/play-silhouette). If you have a feature request, the [mailing list](https://groups.google.com/forum/#!forum/play-silhouette) is a better forum than an issue tracker to discuss it.
