### ISSUE TITLE
Use sbt 0.13.13 g8 generator

### ISSUE THREAD

**Issue by charafau** [mohiva/play-silhouette-seed#99]
Issue copied from: https://github.com/mohiva/play-silhouette/issues/507

Hello, I asked on gitter's room but with no reply.

Since sbt 0.13.13 and play examples with generators, maybe it would be better to create some g8 generators and make it easier to apply silhouette into new project, with sql migrations, forms and everything? Reference links:

```
https://playframework.com/download#starters
would be nice just to write g8Scaffold silhouette and generate migrations, user class and form
```

**Comment by akkie** [comment]
How does the giter8 differ from a seed template? Are they preferred by Play. Are they compatible? I'll not create two different templates for the same application type. That's not maintainable for me.

**Comment by charafau** [comment]
After my background check, g8Scaffold plugin cannot download templates from internet for now. Hope it will change in the future so then we will be able to scaffold registration / login from command line to any project. Let's close it for now.
